version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: options
      POSTGRES_PASSWORD: options
      POSTGRES_DB: options
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
